### PR TITLE
[Proposition] Rename security interface

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

One element I missed in my previous PR was renaming top level interface. 
I think we should:

- define interface names more carefully
- avoid using implementation specifics for interfaces 
- avoid using shorthands for names (prop => Property, Auth => Authorization)

Note: This change is not ready to be merged. Just idea.
 
## Security interface

In this particular case Auth interface suggest that we may deal with Authentication or Authorization. Shorter name causing confusion etc. Our interface is doing both so best to find more top level name. My suggestion in changes.

## Community voting

Vote 👍  👎  
Comments for different name propositions.

### CODE REVIEW

**Comment by JameelB** [comment]
:+1:

**Comment by col1985** [comment]
👍

**Comment by camilamacedo86** [comment]
+1

**Comment by camilamacedo86** [comment]
👍

**Review by darachcawley — CHANGES_REQUESTED** [review]
looks good, perhaps rename the reference on line 42 too

**Review by aidenkeating — COMMENTED** [review]
This looks fine to me

**Comment by wtrocki** [comment]
**Thanks to everyone for voting**  :1st_place_medal: 
We going to incorporate changes in separate PR

**Comment by aidenkeating** [comment]
@wtrocki Actually, one small comment, should it be `SecureEndpoint` rather than `EndpointSecurity`?

To me, `PassportAuth implements SecureEndpoint` reads a bit better. Could be wrong though, haven't looked into the code itself too much so it may not be doing what I am thinking.

**Pull request closed without merging**
